### ISSUE TITLE
trying to use gemini as an LLM 

### ISSUE THREAD

**Issue by MissGorgeousTech** [aiplanethub/openagi#71]
When I need to from openagi.llms.gemini import GeminiModel, it asks me to install ..to install pip install langchain-google-genai and then there is a conflict between dependencies from openAGI mainly with pydandic and is circular. so the flow for this error..is try to install openagi first, then try to use gemini API and import langchain-google-genai and errors of conflicts with dependencies appear. the code really works well with azure.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-google-genai 2.0.0 requires langchain-core<0.4,>=0.3.0, but you have langchain-core 0.1.52 which is incompatible.
langchain-google-genai 2.0.0 requires pydantic<3,>=2, but you have pydantic 1.10.7 which is incompatible.

**Comment by tarun-aiplanet** [comment]
Thanks for addressing the issue, will resolve it

**Comment by lucifertrj** [comment]
https://github.com/aiplanethub/openagi/commit/79cf2563f9faa7aafb8f85e96b450c7aebf4cd3d

we have fixed the dependency issue. The new release will be made by the EOD
