### ISSUE TITLE
Broken Link to Contribution Guidelines in README File

### ISSUE THREAD

**Issue by Bhabuk10** [aiplanethub/openagi#82]
# Broken Link to Contribution Guidelines in README File

**Description:**

While exploring the README file of the OpenAGI repository, I encountered a broken link in the "Contribution Guidelines" section. Specifically, the "please click here" link, which is intended to direct users to a comprehensive guide on the contribution process, leads to a **404 Page Not Found** error.

### Steps to Reproduce:
1. Navigate to the official OpenAGI repository's README file.
2. Scroll down to the **Contribution guidelines** section.
3. Click on the "please click here" hyperlink.

### Expected Behavior:
Clicking on the link should redirect users to the correct and accessible contribution guide.

### Actual Behavior:
The link leads to a **404 Page Not Found** error.

### Snapshot of the Error:
![error](https://github.com/user-attachments/assets/51edba74-9d96-49e2-af9b-6f9c5b05e395)

### Suggested Fix:
Kindly update the broken link to point to the correct contribution guidelines page, ensuring contributors have easy access to the necessary resources.

**Comment by tarun-aiplanet** [comment]
you can open PR to fix this

**Comment by Bhabuk10** [comment]
@tarun-aiplanet After exploring , I noticed that there isn't a CONTRIBUTING.md file in the repo, which might be causing the broken link. Also add relevant labels to this issues .

**Comment by tarun-aiplanet** [comment]
You can create PR and then mark the issue

**Comment by Bhabuk10** [comment]
@tarun-aiplanet  Please review this PR and let me know if any additional changes are needed.

**Comment by tarun-aiplanet** [comment]
#85 merged. Thank you for the PR, closing the comment
